### ISSUE TITLE
SyntaxError

### ISSUE THREAD

**Issue by dafriedman97** [kylemcdonald/covid-mobility-data#3]
I'm getting the following error. I'm very new to all of this so apologies if this is a basic question but any ideas?

`SyntaxError: invalid syntax
pdf/2020-03-29_GR_Mobility_Report_en.pdf
  File "covid-pdf-to-tsv.py", line 190
    yield ('region', region, *result)`

Also, possibly related, when I run `sudo apt install poppler-utils` I get `Unable to locate an executable at "/Library/Java/JavaVirtualMachines/jdk1.8.0_241.jdk/Contents/Home/bin/apt" (-1)`. Any idea there either? Thanks so much!

**Comment by radames** [comment]
@dafriedman97 are you using Mac? this seems like so `"/Library/Java/JavaVirtualMachines/jdk1.8.0_241.jdk/Contents/Home/bin/apt"`. `apt install` is for a debian linux 
if you are on Mac and have [brew](https://brew.sh/) installed you can try 

`brew install poppler`

**Comment by dafriedman97** [comment]
Thanks, I think I just figured that out myself, sadly. I ran `brew install poppler` successfully, but I'm still getting the syntax error. Any idea why? Thanks again

> @dafriedman97 are you using Mac? this seems like so `"/Library/Java/JavaVirtualMachines/jdk1.8.0_241.jdk/Contents/Home/bin/apt"`. `apt install` is for a debian linux
> if you are on Mac and have [brew](https://brew.sh/) installed you can try
> 
> `brew install poppler`

**Comment by radames** [comment]
you need to use python3

**Comment by dafriedman97** [comment]
I think there was an issue with my bash profile but I fixed it. Like I said, still new to this. Thanks for the help
