### ISSUE TITLE
New reports with different start date

### ISSUE THREAD

**Issue by radames** [kylemcdonald/covid-mobility-data#4]
Hi Kyle,
Today they've updated the reports!

I've run your code on all new pdfs, however I've notice the hardcoded starting date 

https://github.com/kylemcdonald/covid-mobility-data/blob/5b4420affd836e0233e4298888097d1da6400d4c/covid-pdf-to-tsv.py#L15

Maybe you can add it as an argument? I've changed it on my local repo and it run fine.

Another tip, the new URL pattern for new reports just change the publication data to `/2020-04-05` in case you want to add to your repository.

https://www.gstatic.com/covid19/mobility/2020-04-05_ZW_Mobility_Report_en.pdf

I'll figure out a way to merge the overlapping data, as the old reports start on `start 2020-02-16 end 2020-03-29` and the new ones `start 2020-02-23 end 2020-04-05`

**Comment by kylemcdonald** [comment]
Thanks! But I'm dropping support for this in favor of this implementation by  @nacnudus https://github.com/nacnudus/google-location-coronavirus which I believe is more robust and more accurate. Please switch to that implementation. Thanks for your help and interest 🙏
